version: "3"

services:
  ogc2ckan:
    container_name: ckan-ogc-dev
    build:
      context: .
      dockerfile: ckan-ogc/Dockerfile.dev
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      # debugpy
      - "${CKAN_OGC_DEV_PORT}:${CKAN_OGC_DEV_PORT}"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
        - ./data:${APP_DIR}/data
        - ./ogc2ckan:${APP_DIR}/ogc2ckan
    network_mode: host