version: "3"

services:
  ogc2ckan:
    container_name: ckan-ogc
    build:
      context: .
      dockerfile: ckan-ogc/Dockerfile.ghcr
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
        - ./data:${APP_DIR}/data
    restart: on-failure:3
    network_mode: host