version: "3"

services:
  ogc2ckan:
    container_name: ckan-ogc-dev
    build:
      context: ckan-ogc/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      # debugpy
      - "5678:5678"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
    network_mode: host