name: ckan-ogc
services:
  ogc2ckan:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/mjanez/ckan-ogc:latest
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
    restart: on-failure:3
networks:
  default:
    name: ogc2ckan_default