FROM ghcr.io/mjanez/ckan-ogc-dev:latest
LABEL maintainer="mnl.janez@gmail.com"

ENV APP_DIR=/app
ENV TZ=UTC
RUN echo ${TZ} > /etc/timezone
ENV CKAN_URL=http://localhost:5000/
ENV PYCSW_URL=http://localhost:8000/
ENV CKAN_API_KEY=ckan-api-key
ENV CKAN_DATASET_MULTILANG=False
ENV DEFAULT_LICENSE=http://creativecommons.org/licenses/by/4.0/
ENV DEFAULT_LICENSE_ID=cc-by
ENV DEV_MODE=False
ENV TIMEOUT=300
ENV CKAN_OGC_DEV_PORT=5678
ENV SSL_UNVERIFIED_MODE=False

WORKDIR ${APP_DIR}

COPY ckan-ogc/conf/config.yaml.template config.yaml
COPY ckan-ogc/docker-entrypoint.d/entrypoint_dev.sh entrypoint.sh

EXPOSE ${CKAN_OGC_DEV_PORT}/TCP

# Set entrypoint with debugpy
ENTRYPOINT ["/bin/bash", "-c", "python3 -m debugpy --listen 0.0.0.0:${CKAN_OGC_DEV_PORT} --wait-for-client ./entrypoint_dev.sh"]

CMD ["tail", "-f", "/dev/null"]